### ISSUE TITLE
error when post test

### ISSUE THREAD

**Issue by cowcomic** [AirCodeLabs/aircode#49]
a function for api proxy

```

module.exports = async function(params, context) {

  const method = context.method;
  const uri = context.headers['uri'];

  delete context.headers.uri;
  
  try {
    const result = await axios.post
      (
        `${url}${uri}`, 
        params,
        {
          headers: context.headers,  
        },
      );
    return result.data;
  } catch (error) {
    console.log('Something wrong:', error.message);
    return {
      error: error,
    };
  }
}
```

debug is OK 
deploy
error when test by postman 

```
Error: write EPROTO 140495407216512:error:14094410:SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:../deps/openssl/openssl/ssl/record/rec_layer_s3.c:1546:SSL alert number 40

    at Function.AxiosError.from (/code/node_modules/axios/dist/node/axios.cjs:829:14)
    at RedirectableRequest.handleRequestError (/code/node_modules/axios/dist/node/axios.cjs:2975:25)
    at RedirectableRequest.emit (node:events:527:28)
    at ClientRequest.eventHandlers.<computed> (/code/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by adcentury** [comment]
As per our [Fair Use Policy](https://docs.aircode.io/about/limits#fair-use-policy), AirCode can not be used as proxies or VPNs. I hope this helps.
